language: python

python:
  - "3.5"


install: 
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - coverage run --source=app.models -m py.test && coverage report
  - coveralls
after_sucess:
  - coveralls